/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_webrtc_SimulcastVideoEncoderFactory */

#ifndef _Included_org_webrtc_SimulcastVideoEncoderFactory
#define _Included_org_webrtc_SimulcastVideoEncoderFactory
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_webrtc_SimulcastVideoEncoderFactory
 * Method:    nativeVP9Codecs
 * Signature: ()Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_org_webrtc_SimulcastVideoEncoderFactory_nativeVP9Codecs
  (JNIEnv *, jclass);

/*
 * Class:     org_webrtc_SimulcastVideoEncoderFactory
 * Method:    nativeAV1Codec
 * Signature: ()Lorg/webrtc/VideoCodecInfo;
 */
JNIEXPORT jobject JNICALL Java_org_webrtc_SimulcastVideoEncoderFactory_nativeAV1Codec
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
