name: Claude Assistant

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]

permissions:
  contents: read
  issues: write
  pull-requests: write
  actions: read

env:
  CLAUDE_API_KEY: ${{ secrets.ANTHROPIC_API_KEY_WEBRTC_BUILD_SONNET }}

jobs:
  claude-response:
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v5
      - uses: shiguredo/github-actions/.github/actions/claude-code-action@main
        with:
          api_key: ${{ env.CLAUDE_API_KEY }}
